# From https://github.com/marketplace/actions/check-spelling-js-vue-html-markdown-text
 
name: Check Spelling
on:
  pull_request:
    paths:
#    - '**.js'
#    - '**.vue'
    - '**.txt'
    - '**.html'
    - '**.md'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: SFLScientific/spellcheck-github-actions@master
